# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='increment',
            field=models.IntegerField(default=0),
        ),
    ]
