# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0003_countdecrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdecrement',
            name='decrement',
            field=models.IntegerField(default=0),
        ),
    ]
