# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0004_auto_20180315_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='CountDecrement',
        ),
    ]
